PC = eval(input("Por favor digite la cantidad de dinero en pesos Colombianos"))
D = PC/3500 - (PC/3500 * 0.2)
print("Peso Colombiano a Dolar: ", D)
Ye = PC/34 - (PC/34 * 0.2)
print("Peso Colombiano a Yenes: ", Ye)
E = PC/4300 - (PC/34 * 0.2)
print("Peso Colombiano a Euro: ", E)